# Generated by Django 5.2.18 on 2026-10-08 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField(help_text='Negative for deductions, positive for increments')),
                ('reason', models.CharField(choices=[('PURCHASE', 'Customer Purchase'), ('RESTOCK', 'Restock / Inbound'), ('RETURN', 'Customer Return'), ('CANCELLATION', 'Order Cancellation'), ('ADJUSTMENT', 'Manual Adjustment')], default='RESTOCK', max_length=30)),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
